# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"1\n\x0bRegisterReq\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\x08LoginReq\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\r\n\x0bValidateReq\"(\n\x08\x41uthResp\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\">\n\x0cValidateResp\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\x91\x01\n\x04\x41uth\x12-\n\x08Register\x12\x11.auth.RegisterReq\x1a\x0e.auth.AuthResp\x12\'\n\x05Login\x12\x0e.auth.LoginReq\x1a\x0e.auth.AuthResp\x12\x31\n\x08Validate\x12\x11.auth.ValidateReq\x1a\x12.auth.ValidateRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQ']._serialized_start=20
  _globals['_REGISTERREQ']._serialized_end=69
  _globals['_LOGINREQ']._serialized_start=71
  _globals['_LOGINREQ']._serialized_end=117
  _globals['_VALIDATEREQ']._serialized_start=119
  _globals['_VALIDATEREQ']._serialized_end=132
  _globals['_AUTHRESP']._serialized_start=134
  _globals['_AUTHRESP']._serialized_end=174
  _globals['_VALIDATERESP']._serialized_start=176
  _globals['_VALIDATERESP']._serialized_end=238
  _globals['_AUTH']._serialized_start=241
  _globals['_AUTH']._serialized_end=386
# @@protoc_insertion_point(module_scope)
